//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Nesty\Desktop\tesis\project\PlPgSqlParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PlPgSqlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IPlPgSqlParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_body([NotNull] PlPgSqlParser.Function_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.function_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_block([NotNull] PlPgSqlParser.Function_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.id_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId_token([NotNull] PlPgSqlParser.Id_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] PlPgSqlParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.start_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart_label([NotNull] PlPgSqlParser.Start_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarations([NotNull] PlPgSqlParser.DeclarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] PlPgSqlParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_declaration([NotNull] PlPgSqlParser.Type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.select_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_stmt([NotNull] PlPgSqlParser.Select_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.select_ops"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_ops([NotNull] PlPgSqlParser.Select_opsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.select_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_primary([NotNull] PlPgSqlParser.Select_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.window_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_definition([NotNull] PlPgSqlParser.Window_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.frame_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_clause([NotNull] PlPgSqlParser.Frame_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.frame_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_bound([NotNull] PlPgSqlParser.Frame_boundContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.orderby_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderby_clause([NotNull] PlPgSqlParser.Orderby_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.sort_specifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSort_specifier_list([NotNull] PlPgSqlParser.Sort_specifier_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.sort_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSort_specifier([NotNull] PlPgSqlParser.Sort_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.null_ordering"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull_ordering([NotNull] PlPgSqlParser.Null_orderingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.order_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder_specification([NotNull] PlPgSqlParser.Order_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.all_op_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll_op_ref([NotNull] PlPgSqlParser.All_op_refContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.all_simple_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll_simple_op([NotNull] PlPgSqlParser.All_simple_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.op_chars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp_chars([NotNull] PlPgSqlParser.Op_charsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.values_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValues_stmt([NotNull] PlPgSqlParser.Values_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.values_values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValues_values([NotNull] PlPgSqlParser.Values_valuesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.partition_by_columns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartition_by_columns([NotNull] PlPgSqlParser.Partition_by_columnsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.schema_qualified_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSchema_qualified_name([NotNull] PlPgSqlParser.Schema_qualified_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.select_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_list([NotNull] PlPgSqlParser.Select_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.select_sublist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_sublist([NotNull] PlPgSqlParser.Select_sublistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.col_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCol_label([NotNull] PlPgSqlParser.Col_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.groupby_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupby_clause([NotNull] PlPgSqlParser.Groupby_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.grouping_element_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouping_element_list([NotNull] PlPgSqlParser.Grouping_element_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.grouping_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouping_element([NotNull] PlPgSqlParser.Grouping_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.from_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrom_item([NotNull] PlPgSqlParser.From_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.from_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrom_primary([NotNull] PlPgSqlParser.From_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.from_function_column_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrom_function_column_def([NotNull] PlPgSqlParser.From_function_column_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_type([NotNull] PlPgSqlParser.Data_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_type([NotNull] PlPgSqlParser.Array_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.predefined_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredefined_type([NotNull] PlPgSqlParser.Predefined_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.schema_qualified_name_nontype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSchema_qualified_name_nontype([NotNull] PlPgSqlParser.Schema_qualified_name_nontypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.identifier_nontype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier_nontype([NotNull] PlPgSqlParser.Identifier_nontypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.interval_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterval_field([NotNull] PlPgSqlParser.Interval_fieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.type_length"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_length([NotNull] PlPgSqlParser.Type_lengthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.precision_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecision_param([NotNull] PlPgSqlParser.Precision_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] PlPgSqlParser.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.xml_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXml_function([NotNull] PlPgSqlParser.Xml_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.xml_table_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXml_table_column([NotNull] PlPgSqlParser.Xml_table_columnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.string_value_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_value_function([NotNull] PlPgSqlParser.String_value_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.date_time_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate_time_function([NotNull] PlPgSqlParser.Date_time_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.system_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSystem_function([NotNull] PlPgSqlParser.System_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.cast_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCast_specification([NotNull] PlPgSqlParser.Cast_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.extract_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtract_function([NotNull] PlPgSqlParser.Extract_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.character_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacter_string([NotNull] PlPgSqlParser.Character_stringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.function_construct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_construct([NotNull] PlPgSqlParser.Function_constructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.filter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilter_clause([NotNull] PlPgSqlParser.Filter_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.vex_or_named_notation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVex_or_named_notation([NotNull] PlPgSqlParser.Vex_or_named_notationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointer([NotNull] PlPgSqlParser.PointerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.table_subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_subquery([NotNull] PlPgSqlParser.Table_subqueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.names_in_parens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNames_in_parens([NotNull] PlPgSqlParser.Names_in_parensContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.names_references"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNames_references([NotNull] PlPgSqlParser.Names_referencesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.alias_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias_clause([NotNull] PlPgSqlParser.Alias_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.into_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInto_table([NotNull] PlPgSqlParser.Into_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.set_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_qualifier([NotNull] PlPgSqlParser.Set_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.with_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_clause([NotNull] PlPgSqlParser.With_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.with_query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_query([NotNull] PlPgSqlParser.With_queryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.delete_stmt_for_psql"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelete_stmt_for_psql([NotNull] PlPgSqlParser.Delete_stmt_for_psqlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.update_stmt_for_psql"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdate_stmt_for_psql([NotNull] PlPgSqlParser.Update_stmt_for_psqlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.update_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdate_set([NotNull] PlPgSqlParser.Update_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.indirection_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndirection_identifier([NotNull] PlPgSqlParser.Indirection_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.indirection_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndirection_list([NotNull] PlPgSqlParser.Indirection_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.indirection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndirection([NotNull] PlPgSqlParser.IndirectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.insert_stmt_for_psql"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsert_stmt_for_psql([NotNull] PlPgSqlParser.Insert_stmt_for_psqlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.conflict_action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConflict_action([NotNull] PlPgSqlParser.Conflict_actionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.conflict_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConflict_object([NotNull] PlPgSqlParser.Conflict_objectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.index_where"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_where([NotNull] PlPgSqlParser.Index_whereContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.index_sort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_sort([NotNull] PlPgSqlParser.Index_sortContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.insert_columns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsert_columns([NotNull] PlPgSqlParser.Insert_columnsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.after_ops"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAfter_ops([NotNull] PlPgSqlParser.After_opsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.arguments_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments_list([NotNull] PlPgSqlParser.Arguments_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.collate_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollate_identifier([NotNull] PlPgSqlParser.Collate_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.data_type_dec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_type_dec([NotNull] PlPgSqlParser.Data_type_decContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.exception_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitException_statement([NotNull] PlPgSqlParser.Exception_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.function_statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_statements([NotNull] PlPgSqlParser.Function_statementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.function_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_statement([NotNull] PlPgSqlParser.Function_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.base_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_statement([NotNull] PlPgSqlParser.Base_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.diagnostic_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiagnostic_option([NotNull] PlPgSqlParser.Diagnostic_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar([NotNull] PlPgSqlParser.VarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.perform_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPerform_stmt([NotNull] PlPgSqlParser.Perform_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.control_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControl_statement([NotNull] PlPgSqlParser.Control_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_stmt([NotNull] PlPgSqlParser.Return_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.explain_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplain_statement([NotNull] PlPgSqlParser.Explain_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.explain_query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplain_query([NotNull] PlPgSqlParser.Explain_queryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.create_table_as_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_table_as_statement([NotNull] PlPgSqlParser.Create_table_as_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.storage_parameter_oid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorage_parameter_oid([NotNull] PlPgSqlParser.Storage_parameter_oidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.with_storage_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_storage_parameter([NotNull] PlPgSqlParser.With_storage_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.storage_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorage_parameter([NotNull] PlPgSqlParser.Storage_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.storage_parameter_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorage_parameter_option([NotNull] PlPgSqlParser.Storage_parameter_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.on_commit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOn_commit([NotNull] PlPgSqlParser.On_commitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.table_space"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_space([NotNull] PlPgSqlParser.Table_spaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.if_not_exists"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_not_exists([NotNull] PlPgSqlParser.If_not_existsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.create_view_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_view_statement([NotNull] PlPgSqlParser.Create_view_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.view_columns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitView_columns([NotNull] PlPgSqlParser.View_columnsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.with_check_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_check_option([NotNull] PlPgSqlParser.With_check_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.execute_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecute_statement([NotNull] PlPgSqlParser.Execute_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.declare_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare_statement([NotNull] PlPgSqlParser.Declare_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.explain_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplain_option([NotNull] PlPgSqlParser.Explain_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.boolean_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_value([NotNull] PlPgSqlParser.Boolean_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.show_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShow_statement([NotNull] PlPgSqlParser.Show_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.execute_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecute_stmt([NotNull] PlPgSqlParser.Execute_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] PlPgSqlParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.case_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_statement([NotNull] PlPgSqlParser.Case_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop_statement([NotNull] PlPgSqlParser.Loop_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.loop_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop_start([NotNull] PlPgSqlParser.Loop_startContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOption([NotNull] PlPgSqlParser.OptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier_list([NotNull] PlPgSqlParser.Identifier_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.transaction_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransaction_statement([NotNull] PlPgSqlParser.Transaction_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.lock_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLock_table([NotNull] PlPgSqlParser.Lock_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.lock_mode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLock_mode([NotNull] PlPgSqlParser.Lock_modeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.only_table_multiply"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnly_table_multiply([NotNull] PlPgSqlParser.Only_table_multiplyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.cursor_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCursor_statement([NotNull] PlPgSqlParser.Cursor_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.fetch_move_direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFetch_move_direction([NotNull] PlPgSqlParser.Fetch_move_directionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.signed_number_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSigned_number_literal([NotNull] PlPgSqlParser.Signed_number_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSign([NotNull] PlPgSqlParser.SignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.message_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessage_statement([NotNull] PlPgSqlParser.Message_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.raise_using"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaise_using([NotNull] PlPgSqlParser.Raise_usingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.raise_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaise_param([NotNull] PlPgSqlParser.Raise_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.log_level"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLog_level([NotNull] PlPgSqlParser.Log_levelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.data_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_statement([NotNull] PlPgSqlParser.Data_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.notify_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotify_stmt([NotNull] PlPgSqlParser.Notify_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.truncate_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTruncate_stmt([NotNull] PlPgSqlParser.Truncate_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.cascade_restrict"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCascade_restrict([NotNull] PlPgSqlParser.Cascade_restrictContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.additional_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditional_statement([NotNull] PlPgSqlParser.Additional_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.copy_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopy_statement([NotNull] PlPgSqlParser.Copy_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.copy_from_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopy_from_statement([NotNull] PlPgSqlParser.Copy_from_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.copy_to_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopy_to_statement([NotNull] PlPgSqlParser.Copy_to_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.user_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUser_name([NotNull] PlPgSqlParser.User_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.copy_option_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopy_option_list([NotNull] PlPgSqlParser.Copy_option_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.copy_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopy_option([NotNull] PlPgSqlParser.Copy_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.truth_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTruth_value([NotNull] PlPgSqlParser.Truth_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.table_cols_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_cols_list([NotNull] PlPgSqlParser.Table_cols_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.table_cols"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_cols([NotNull] PlPgSqlParser.Table_colsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.anonymous_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymous_block([NotNull] PlPgSqlParser.Anonymous_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.analyze_mode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnalyze_mode([NotNull] PlPgSqlParser.Analyze_modeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.using_vex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsing_vex([NotNull] PlPgSqlParser.Using_vexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign_stmt([NotNull] PlPgSqlParser.Assign_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.select_stmt_no_parens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_stmt_no_parens([NotNull] PlPgSqlParser.Select_stmt_no_parensContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.select_ops_no_parens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_ops_no_parens([NotNull] PlPgSqlParser.Select_ops_no_parensContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.vex_b"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVex_b([NotNull] PlPgSqlParser.Vex_bContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOp([NotNull] PlPgSqlParser.OpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.value_expression_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_expression_primary([NotNull] PlPgSqlParser.Value_expression_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.datetime_overlaps"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetime_overlaps([NotNull] PlPgSqlParser.Datetime_overlapsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.type_coercion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_coercion([NotNull] PlPgSqlParser.Type_coercionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.array_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_expression([NotNull] PlPgSqlParser.Array_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.array_elements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_elements([NotNull] PlPgSqlParser.Array_elementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.indirection_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndirection_var([NotNull] PlPgSqlParser.Indirection_varContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.dollar_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDollar_number([NotNull] PlPgSqlParser.Dollar_numberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.comparison_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison_mod([NotNull] PlPgSqlParser.Comparison_modContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.case_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_expression([NotNull] PlPgSqlParser.Case_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.unsigned_value_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnsigned_value_specification([NotNull] PlPgSqlParser.Unsigned_value_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.unsigned_numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnsigned_numeric_literal([NotNull] PlPgSqlParser.Unsigned_numeric_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.type_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_list([NotNull] PlPgSqlParser.Type_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.vex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVex([NotNull] PlPgSqlParser.VexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.tokens_nonreserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTokens_nonreserved([NotNull] PlPgSqlParser.Tokens_nonreservedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.tokens_nonreserved_except_function_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTokens_nonreserved_except_function_type([NotNull] PlPgSqlParser.Tokens_nonreserved_except_function_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.tokens_reserved_except_function_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTokens_reserved_except_function_type([NotNull] PlPgSqlParser.Tokens_reserved_except_function_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.tokens_reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTokens_reserved([NotNull] PlPgSqlParser.Tokens_reservedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlPgSqlParser.tokens_nonkeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTokens_nonkeyword([NotNull] PlPgSqlParser.Tokens_nonkeywordContext context);
}
